import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, CardHeader, CardBody, CardFooter, Text, SimpleGrid, Heading, Button } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // Array para armazenar os dados dos cartões
  const cardsData = Array.from({ length: 20 }, (_, index) => ({
    title: `Customer dashboard ${index + 1}`,
    description: "View a summary of all your customers over the last month."
  }));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Home</h1>
      </main>
    </>
  );
}
